namespace      = "objective-reality-gaming"
region         = "us-east-1"
ip_addresses   = ["mine"]
instance_type  = "g5.xlarge"
volume_size    = 250
volume_type    = "gp3"
admin_password = "TheAbstract22!"
ec2_count      = 1
ami            = "ami-0fb9b998f0dc61cb8"
# ami_owner      = "amazon"                        # for cloudxr "aws-marketplace"
# ami_filter     = "DCV-Windows-*-NVIDIA-gaming-*" # for cloudxr "win2019-server-vWS-472.39-cloudxr-v3.1_ami2-*"